### PR TITLE
Pass the secret_key to update_sale_with_charge.

### PR DESCRIPTION
**Pull request by jagthedrummer**
Resolves Issue #106.

### CODE REVIEW

**Comment by jagthedrummer** [comment]
Looks like there are tests failing on this branch, but they're also failing on master...

**Comment by peterkeen** [comment]
Yeah, the tests are failing because of an interaction between Stripe::Mock and the Stripe bindings >= v1.20.2. I'm going to peg us at v1.20.1 for now (later this afternoon, likely) and see what I can do about a Stripe::Mock fix.

https://github.com/rebelidealist/stripe-ruby-mock/pull/200

**Comment by peterkeen** [comment]
@jagthedrummer could you rebase onto master please? I'll cut v1.3.1 after we get a green build on this PR.

**Comment by jagthedrummer** [comment]
OK, rebased and force pushed.

**Pull request merged**
