### PR TITLE
Lemuelbarango/update stripe gem

### PR DESCRIPTION
**Pull request by lemuelbarango**
Unpegged stripe version and passed test

### CODE REVIEW

**Comment by eliotsykes** [comment]
The `Stripe.api_key` value is shared amongst threads. 

Using `Stripe.api_key = ...` would cause problems with apps using more than one Stripe API key across multiple threads. 

If Payola continues support for multiple API keys, then the API key would need to be passed in as an argument to the `retrieve` calls as before.

As far as anything else goes with unpegging the stripe-ruby version, I'm hoping other reviewers can weigh in.

**Comment by eliotsykes** [comment]
Also forgot to say thank you for opening the PR @lemuelbarango! 👍

**Comment by peterkeen** [comment]
I agree with @eliotsykes on both counts: first, thank you for opening the PR! And second, this isn't quite the right approach. The correct way to do this would be something like:

```
secret_key = Payola.secret_key_for_sale(subscription)
customer = Stripe::Customer.retrieve(subscription.stripe_customer_id, {api_key: secret_key})
```

Note the hash as the second argument that replaces the string argument. That will set the API key for *just that request* instead of globally. Your method, as Elliot pointed out, will cause major issues in threaded environments.

**Comment by peterkeen** [comment]
@lemuelbarango if you inspect the `secret_key` in your modifications, I'll bet most of the time you'll see it's actually `nil`, which is the root of the problem (and extremely embarrassing that I didn't catch that months ago). Stripe didn't change their API but along the way they got more strict about it actually being a string or a hash.

If you add this to `spec/spec_helper.rb` somewhere you'll find that your first commit is *almost* sufficient:

```
ENV['STRIPE_SECRET_KEY'] = 'sk_testing123'
ENV['STRIPE_PUBLISHABLE_KEY'] = 'pk_test123'
```

After those are set all you need are those `expect`s on `Stripe::BalanceTransaction.retrieve`. You don't have to change any of the `retrieve` or `create` calls.

**Comment by lemuelbarango** [comment]
Thanks for the suggestion @peterkeen I'll update my PR

**Comment by lemuelbarango** [comment]
updated the PR

**Comment by peterkeen** [comment]
Looks good to me. @eliotsykes?

**Comment by eliotsykes** [comment]
Agreed 👍

@peterkeen, @lemuelbarango what do you think about experimenting with asking contributors to add their own changelog entry for their work as part of their PR?

**Comment by lemuelbarango** [comment]
@eliotsykes not a bad idea

**Comment by lemuelbarango** [comment]
^^

**Comment by peterkeen** [comment]
👍

**Comment by eliotsykes** [comment]
Thanks @lemuelbarango 👍

**Pull request merged**
