### PR TITLE
Feature/accept tax percent for subs

### PR DESCRIPTION
**Pull request by paulccarey**
* This resolves the issue when setting up subscriptions and needing to apply a tax percent for the subscription as per issue #103 

* You can either set the default tax_percent using 
```ruby
Payola.configure do |config|
  config.default_tax_percent = 20
end
```
* or you can pass in the tax_percent to the subscription checkout partial as a whole number (as per Stripe docs)
```ruby
<%= render 'payola/subscriptions/checkout', plan: plan, email: email, tax_percent: 20 %>
```

The price including vat is then displayed when using checkout.

### CODE REVIEW

**Comment by jharbert** [comment]
@paulccarey - Any reason why the tax percent is implemented as an integer value?

https://github.com/peterkeen/payola/pull/167/files#diff-6153753afa51e53dbd05fcbf543eef90R3
https://github.com/peterkeen/payola/pull/167/files#diff-60a791f607e21a9fc3fb93eb16e61bb2R28

What about cases where the tax rate is a decimal, e.g. 9.5%?

**Comment by paulccarey** [comment]
hey @jharbert I simply didn't consider decimal values!

As you point out an improvement would be to accept decimals here, should be a minor job to fix.

**Comment by peterkeen** [comment]
Geeze, that's a good point @jharbert.

@paulccarey could you submit another pull that does that fix please? A simple migration that changes the column type should be sufficient. Thanks!

**Comment by paulccarey** [comment]
I'll leave this with @jharbert to scratch this itch :wink:

**Comment by fastdivision** [comment]
Couldn't wait any longer ;) Went ahead and converted to decimal in #189

**Pull request merged**
