### PR TITLE
Rs/create coupon with stripe

### PR DESCRIPTION
**Pull request by rschooley**
This PR adds more functionality for working with coupons:

1. add ```amount_off```
2. add ```duration``` & ```duration_in_months``` (with Stripe rules)
3. add CreateCoupon service to sync coupon creation with Stripe

### CODE REVIEW

**Comment by rschooley** [comment]
One thing to note is I changed models/payola/coupon_spec to use a factory because of the required field.  It cut down on a bunch of repeated code with ```Coupon.create(code: "abc", duration: "once")```.

**Comment by peterkeen** [comment]
There's a bit of a disconnect here. Payola-level coupons apply to one-off purchases, not subscriptions. Stripe doesn't let you pass a coupon code to a one-off charge.

When we do coupons for subscriptions we just pass the opaque coupon id to Stripe.

Sorry. This should probably be documented better.

**Comment by rschooley** [comment]
I am not sure I follow.  The PR doesn't involve one off purchases or subscriptions, it adds features to the core coupons domain object.

1) It looks like amount_off was added at some point in Stripe, but Payola only has percent_off
2) There is also duration and duration_in_months on the Stripe side that isn't in the current payola_coupon table
3) The service allows creating a coupon in Payola to be sent to Stripe so they can be managed in an app.

ref: https://stripe.com/docs/api/ruby#create_coupon

**Comment by peterkeen** [comment]
The Payola coupon domain object does not apply to subscriptions. It only
applies to one-off purchases. Stripe coupons can't apply to charges, which
is why I made it in the first place.

**Comment by rschooley** [comment]
The coupon.code is applied to subscriptions.  The code lives in the coupon domain object, and there can be rules on how a coupon can be applied in an app.

Use case:
We have a $100 plan and a $200 plan.  A customer can apply a one time coupon for a discount of $100 to upgrade to the more expensive plan.  

This coupon lives in Stripe, but it's also in the database.  Currently the payola table is missing amount_off, it only has percent_off.  It also does not have the duration information.  The coupon in the database is missing information that is in Stripe.  The same data is in two places but it is not the same.  This branch makes them the same and syncs them from an app to Stripe.

Currently a user has to go into Stripe to make a coupon with amount_off and duration, then put them in the database, but the information in the db is incomplete.

screen shot 2015-07-29 at 4 09 05 pm

**Comment by peterkeen** [comment]
I understand what you're saying. You want Payola coupons to be Stripe coupons. They're not. Payola supports passing a coupon code as a text string through to Stripe to apply to a subscription.

If you want to manage Stripe coupons these in your app, that's fine, but conflating them with Payola's coupons is a mistake. Maybe this should be a new domain object, like `Payola::SubscriptionCoupon`.

**Pull request closed without merging**
