### PR TITLE
Use users stripe_id to find customer if exists

### PR DESCRIPTION
**Pull request by Jakedavies**
… starting sub

### CODE REVIEW

**Comment by peterkeen** [comment]
Talk to me about how this is superior to the logic that's already there. As far as I can tell all you're adding is moving the `stripe_customer_id` onto the subscription owner, in favor of the logic that's already there which stores it on the `Payola::Subscription`.

Also, the migration needs to be in the `spec/dummy/db/migrate` folder, not the root `db/migrate` folder. Payola itself has no concept of a `User`.

**Comment by Jakedavies** [comment]
Moving the logic to have the option of being attached to the subscription owner allows actions to be performed on existing users, my specific application required me to create stripe customers upon user sign up, and increase their stripe balance before they subscribed to anything. Using this new option you are now able to do that.

**Comment by nfm** [comment]
See also #170 - I've just opened a PR that lets you specify the `stripe_customer_id` to be used when starting a subscription, but it doesn't require moving the customer ID to the subscription owner.

**Comment by jharbert** [comment]
It would be nice to be able to get the `stripe_customer_id` after processing a sale/subscription and update the customer (e.g. User model).  Currently, I'm using Stripe's webhooks to accomplish this

**Comment by nfm** [comment]
@jharbert I'm tackling this by subscribing to the 'payola.subscription.active' event, something like this:

```ruby
config.subscribe 'payola.subscription.active' do |subscription|
  subscription.owner.update_attributes(stripe_customer_id: subscription.stripe_customer_id)
end
```

That way you don't have to wait for a webhook.

**Pull request closed without merging**
